service: joshuas-static-blog

plugins:
  - serverless-s3-sync

# Hosted zone information taken from
# https://docs.aws.amazon.com/general/latest/gr/rande.html

custom:
  bucketName: joshuacol.es
  siteName: joshuacol.es
  aliasHostedZoneId: Z3AQBSTGFYJSTF
  aliasDNSName: s3-website-us-east-1.amazonaws.com
  s3Sync:
    - bucketName: ${self:custom.bucketName}
      localDir: ../jekyll/_site

provider:
  name: aws
  runtime: python3.6
  region: us-east-1

resources:

  Resources:

    StaticSite:
      Type: AWS::S3::Bucket
      Properties:
        AccessControl: "PublicRead"
        BucketName: ${self:custom.bucketName}
        WebsiteConfiguration:
          IndexDocument: index.html
          ErrorDocument: index.html

    StaticSiteS3BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          Ref: StaticSite
        PolicyDocument:
          Statement:
            - Sid: PublicReadGetObject
              Effect: Allow
              Principal: "*"
              Action:
                - "s3:GetObject"
              Resource:
                Fn::Join: [
                  "", [
                    "arn:aws:s3:::",
                    {
                      "Ref": "StaticSite"
                    },
                    "/*"
                  ]
                ]

  Outputs:
    StaticSite:
      Value:
        Ref: StaticSite
      Export:
        Name: StaticSite
