service: joshuas-cdn


# Hosted zone information taken from
# https://docs.aws.amazon.com/general/latest/gr/rande.html

custom:
  bucketName: joshuacol.es
  siteName: joshuacol.es
  aliasHostedZoneId: Z2FDTNDATAQYW2
  aliasDNSName: s3-website-us-east-1.amazonaws.com


provider:
  name: aws
  runtime: python3.6
  region: us-east-1

resources:

  Resources:
    
    SiteCDN:
      Type: "AWS::CloudFront::Distribution"
      Properties:
        DistributionConfig:
          PriceClass: "PriceClass_100"
          Aliases:
            - "joshuacol.es"
          Origins:
            - DomainName: "${self:custom.bucketName}.${self:custom.aliasDNSName}"
              Id: "static_blog_origin"
              CustomOriginConfig:
                OriginProtocolPolicy: "http-only"
                HTTPPort: 80
                HTTPSPort: 443
          Enabled: true
          DefaultRootObject: "index.html"
          DefaultCacheBehavior:
            TargetOriginId: "static_blog_origin"
            ForwardedValues:
              QueryString: false
              Cookies:
                Forward: "none"
            ViewerProtocolPolicy: "redirect-to-https"
          ViewerCertificate:
            SslSupportMethod: "sni-only"
            AcmCertificateArn: ${cf:joshuas-certificate-dev.AcmCertificate}
          Logging:
            Bucket: ${cf:joshuas-static-blog-dev.LogBucketAddress}
            IncludeCookies: false
            Prefix: "cdn"

    DnsRecordA:
      Type: "AWS::Route53::RecordSet"
      Properties:
        AliasTarget:
          DNSName: { "Fn::GetAtt": ["SiteCDN", "DomainName"] }
          # https://stackoverflow.com/questions/39665214/get-hosted-zone-for-cloudfront-distribution
          # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-aliastarget.html
          HostedZoneId: "${self:custom.aliasHostedZoneId}"
        HostedZoneName: ${self:custom.siteName}.
        Name: ${cf:joshuas-static-blog-dev.StaticSite}
        Type: "A"

    DnsRecordAAAA:
      Type: "AWS::Route53::RecordSet"
      Properties:
        AliasTarget:
          DNSName: { "Fn::GetAtt": ["SiteCDN", "DomainName"] }
          # https://stackoverflow.com/questions/39665214/get-hosted-zone-for-cloudfront-distribution
          # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-aliastarget.html
          HostedZoneId: "${self:custom.aliasHostedZoneId}"
        HostedZoneName: ${self:custom.siteName}.
        Name: ${cf:joshuas-static-blog-dev.StaticSite}
        Type: "AAAA"
